# basic options
title: Under Construction
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes
